version: '3.7'
services:
    logger-service:
        build: ./loggerserver
        depends_on:
            - 'rabbitmq'
        command: ['./wait-for-it.sh', 'rabbitmq-service:5672', '--timeout=10', '--', 'node', 'rpc_server.js']
        environment:
            - ENV_TYPE=COMPOSE
        volumes:
            - './loggerserver:/home/node/app'
    rabbitmq:
        build: ./rabbitmq
        expose:
            - "5672"
        environment:
            - ENV_TYPE=COMPOSE
        ports:
            - 25672:15672
            - 5672:5672